#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Byrd_REPO == "BygByrd" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $Byrd_REPO == "BygByrd" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $Byrd_REPO =~ $regex ]]
    then
        if [[ $Byrd_REPO_BRANCH ]]
        then
            echo "${BygByrd_Repo}/archive/${HELL_REPO_BRANCH}.zip"
        else
            echo "${BygByrd_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="BygByrd.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    ByrdPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "    Starting BygByrd    "
    echo "
‌‌‎ ______   ______ 
| __ ) \ / / ___|
|  _ \\ V / |  _ 
| |_) || || |_| |
|____/ |_| \____|  __
| __ ) \ / /  _ \|  _ \ 
|  _ \\ V /| |_) | | | |
| |_) || | |  _ <| |_| |
|____/ |_| |_| \_\____/

    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
